<?php

namespace Database\Seeders;

use App\Core\Models\CommunityContentItem;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CommunityContentSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $guides = [
            [
                'title' => 'Getting Started with Peptide Research',
                'slug' => 'getting-started-peptide-research',
                'category' => 'Getting Started',
                'category_slug' => 'getting-started',
                'tag' => 'basics',
                'excerpt' => 'A beginner-friendly overview of peptide research, common terminology, and what you need to know before getting started.',
                'icon' => 'library',
                'read_minutes' => 8,
                'author_name' => 'PeptideGuide',
                'author_badge' => 'Contributor',
                'metadata' => [
                    'difficulty' => 'Beginner',
                    'guide_type' => 'Guide',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Understand What Peptides Are', 'text' => 'Peptides are short chains of amino acids linked by peptide bonds. They occur naturally in the body and serve as signaling molecules, influencing various physiological processes.', 'icon' => 'library'],
                        ['title' => 'Learn Common Terminology', 'text' => 'Familiarize yourself with key terms: reconstitution, lyophilization, bacteriostatic water, molecular weight, purity, and assay. These will appear in every product listing and study.', 'icon' => 'bookmark'],
                        ['title' => 'Review Safety Fundamentals', 'text' => 'Always use sterile techniques, handle with care, and understand the legal and safety landscape. Peptide research should be conducted responsibly.', 'icon' => 'shield'],
                        ['title' => 'Start with Trusted Resources', 'text' => 'Bookmark peer-reviewed studies, community guides, and verified vendor reviews. Cross-reference all information before making decisions.', 'icon' => 'star'],
                    ],
                ],
                'body' => "## What Are Peptides?\n\nPeptides are short chains of amino acids, typically comprising 2\u201350 residues, linked by peptide bonds. They exist throughout nature and play critical roles in biological signaling, hormone regulation, and cellular communication.\n\nUnlike proteins, which are larger and more complex, peptides are small enough to be synthesized in a laboratory and studied for their specific biological effects. This makes them a valuable tool in research settings.\n\n## Key Terminology\n\n- **Reconstitution** \u2014 The process of dissolving lyophilized (freeze-dried) peptide powder into a sterile solution for study\n- **Lyophilization** \u2014 Freeze-drying that removes water to preserve peptide stability\n- **Bacteriostatic Water** \u2014 Sterile water containing 0.9% benzyl alcohol, commonly used for reconstitution\n- **Purity** \u2014 The percentage of the desired peptide in a sample, measured by HPLC\n- **Assay** \u2014 A test method to determine peptide content and purity\n\n## Research Best Practices\n\nProper documentation is essential. Keep detailed records of sourcing, storage conditions, reconstitution dates, and observations. This ensures reproducibility and supports the broader research community.\n\n### Before You Begin\n\n- Verify your source through community reviews and lab test results\n- Understand the legal status of any compound in your jurisdiction\n- Ensure you have proper equipment: sterile vials, syringes, bacteriostatic water, storage containers\n- Set up a clean, organized workspace\n\n## Building Knowledge Gradually\n\nStart with well-characterized, commonly studied peptides. Read published research, compare findings across multiple sources, and engage with the community to learn from experienced researchers.",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(30),
                'views_count' => 1540,
                'image_index' => 0,
            ],
            [
                'title' => 'Proper Reconstitution Techniques',
                'slug' => 'proper-reconstitution-techniques',
                'category' => 'Protocols',
                'category_slug' => 'protocols',
                'tag' => 'reconstitution',
                'excerpt' => 'Step-by-step guide to safely and accurately reconstituting lyophilized peptides for research use.',
                'icon' => 'flask',
                'read_minutes' => 10,
                'author_name' => 'LabProtocols',
                'author_badge' => 'Verified Researcher',
                'metadata' => [
                    'difficulty' => 'Intermediate',
                    'guide_type' => 'Protocol',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Gather Your Materials', 'text' => 'You will need: lyophilized peptide vial, bacteriostatic water, alcohol swabs, sterile syringe with needle, gloves, and a clean workspace.', 'icon' => 'box'],
                        ['title' => 'Sanitize and Prepare', 'text' => 'Wash hands thoroughly, put on gloves, and wipe all vial tops with alcohol swabs. Allow them to air dry before proceeding.', 'icon' => 'shield'],
                        ['title' => 'Inject the Bacteriostatic Water', 'text' => 'Draw the appropriate volume of bacteriostatic water into your syringe. Slowly inject it down the inner wall of the peptide vial to avoid disturbing the powder.', 'icon' => 'flask'],
                        ['title' => 'Swirl Gently to Dissolve', 'text' => 'Do not shake the vial. Gently swirl or roll it until the powder is fully dissolved. Shaking can damage the peptide structure.', 'icon' => 'flask'],
                        ['title' => 'Refrigerate and Store', 'text' => 'Label the vial with the date and concentration. Store in a refrigerator at 2\u20138\u00b0C. Use within the recommended timeframe.', 'icon' => 'clock'],
                    ],
                ],
                'body' => "## Why Proper Reconstitution Matters\n\nReconstitution is the process of dissolving lyophilized (freeze-dried) peptide powder into a sterile solution. Doing this correctly preserves peptide integrity, ensures accurate dosing, and maintains sterility.\n\nImproper technique can lead to peptide degradation, contamination, or inaccurate concentrations \u2014 all of which compromise research results.\n\n## Choosing the Right Solvent\n\n### Bacteriostatic Water\n\nBacteriostatic water (0.9% benzyl alcohol in water) is the most common choice. The benzyl alcohol inhibits bacterial growth, allowing multiple uses from a single vial over several days or weeks.\n\n### Sterile Water vs. Bacteriostatic Water\n\n- **Sterile water** \u2014 Use only for single-dose applications. It contains no preservative and should be used immediately after reconstitution.\n- **Bacteriostatic water** \u2014 Preferred for multi-use vials. It remains sterile for up to 28 days after first use when stored properly.\n\n## Step-by-Step Protocol\n\n- Clean all surfaces and materials with alcohol\n- Allow alcohol to evaporate fully before opening vials\n- Inject solvent slowly to minimize foaming\n- Swirl gently \u2014 never shake or vortex\n- Inspect for particles or cloudiness before use\n- Refrigerate immediately after reconstitution\n\n## Common Mistakes to Avoid\n\n- **Shaking the vial** \u2014 Creates bubbles and can denature the peptide\n- **Using too much or too little solvent** \u2014 Affects concentration accuracy\n- **Reusing a syringe** \u2014 Risks contamination\n- **Storing at room temperature** \u2014 Accelerates degradation\n\n## Storage After Reconstitution\n\nMost reconstituted peptides remain stable for 7\u201314 days at 2\u20138\u00b0C. Always check the specific peptide\u2019s stability profile, as some degrade faster than others. Discard if the solution appears cloudy or contains particulates.",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(25),
                'views_count' => 2100,
                'image_index' => 1,
            ],
            [
                'title' => 'Understanding Peptide Purity and Testing',
                'slug' => 'understanding-peptide-purity-testing',
                'category' => 'Sourcing',
                'category_slug' => 'sourcing',
                'tag' => 'purity',
                'excerpt' => 'Learn how to read and interpret HPLC analysis reports, understand purity grades, and verify quality through third-party testing.',
                'icon' => 'shield',
                'read_minutes' => 12,
                'author_name' => 'QualityCheck',
                'author_badge' => 'Lab Analyst',
                'metadata' => [
                    'difficulty' => 'Intermediate',
                    'guide_type' => 'Guide',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Understand Purity Grades', 'text' => 'Research-grade peptides typically range from 95% to 99%+ purity. Higher purity means fewer impurities and more reliable results.', 'icon' => 'chart'],
                        ['title' => 'Learn to Read HPLC Reports', 'text' => 'HPLC (High-Performance Liquid Chromatography) separates and quantifies peptide components. The main peak represents the target peptide; smaller peaks indicate impurities.', 'icon' => 'document'],
                        ['title' => 'Verify Mass Spectrometry Data', 'text' => 'Mass spectrometry confirms the molecular weight of the peptide, verifying its identity. The measured mass should match the theoretical mass within an acceptable tolerance.', 'icon' => 'flask'],
                        ['title' => 'Check for Third-Party Testing', 'text' => 'Independent lab verification provides an unbiased assessment of purity. Always look for batch-specific COAs from reputable testing laboratories.', 'icon' => 'shield'],
                    ],
                ],
                'body' => "## Why Purity Matters\n\nPurity is one of the most critical factors in peptide research. Impurities can confound results, introduce variability, and compromise the validity of your findings.\n\nA peptide with 98% purity contains 2% impurities, which could include truncated sequences, oxidation products, or residual solvents from synthesis.\n\n## HPLC Analysis\n\nHigh-Performance Liquid Chromatography (HPLC) is the gold standard for purity analysis. The chromatogram shows a main peak at the retention time of the target peptide.\n\n### What to Look For\n\n- **Single dominant peak** \u2014 Indicates high purity\n- **Symmetrical peak shape** \u2014 Suggests a homogeneous product\n- **No fronting or tailing** \u2014 Avoids ambiguity in integration\n- **Baseline separation** \u2014 Ensures accurate quantification\n\n## Mass Spectrometry (MS)\n\nMass spectrometry confirms peptide identity by measuring its molecular weight. The measured mass should match the theoretical mass.\n\n### Acceptable Tolerance\n\nA mass accuracy within \u00b10.5 Da is generally acceptable for most research peptides. Larger deviations may indicate incorrect synthesis or degradation.\n\n## Certificate of Analysis (COA)\n\nA COA from an independent laboratory provides documented evidence of purity and identity. Verify that:\n\n- The batch number matches your product\n- The testing date is recent\n- The purity meets your requirements\n- The lab is accredited and reputable\n\n## Red Flags\n\n- No COA available or refusal to provide one\n- Purity claims above 99% without supporting data\n- Vague or incomplete testing documentation\n- Significantly lower prices than market average",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(20),
                'views_count' => 1870,
                'image_index' => 2,
            ],
            [
                'title' => 'Peptide Storage Best Practices',
                'slug' => 'peptide-storage-best-practices',
                'category' => 'Storage',
                'category_slug' => 'storage',
                'tag' => 'storage',
                'excerpt' => 'Proper storage is essential for maintaining peptide stability and potency. Learn how to store both lyophilized and reconstituted peptides.',
                'icon' => 'box',
                'read_minutes' => 7,
                'author_name' => 'StableGuide',
                'author_badge' => 'Contributor',
                'metadata' => [
                    'difficulty' => 'Beginner',
                    'guide_type' => 'Guide',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Store Lyophilized Peptides in the Freezer', 'text' => 'Keep lyophilized peptides at -20\u00b0C in a frost-free freezer. Avoid temperature fluctuations and freeze-thaw cycles.', 'icon' => 'box'],
                        ['title' => 'Protect from Light and Moisture', 'text' => 'Store vials in a dark, dry place. Use desiccant packs in storage containers to control humidity.', 'icon' => 'shield'],
                        ['title' => 'Label Everything Clearly', 'text' => 'Include the peptide name, molecular weight, amount, reconstitution date, and concentration on every vial.', 'icon' => 'bookmark'],
                        ['title' => 'Monitor Expiry Dates', 'text' => 'Track both the manufacturer expiry and the post-reconstitution use-by date. Discard any peptide past its recommended storage period.', 'icon' => 'calendar'],
                    ],
                ],
                'body' => "## Storage Fundamentals\n\nPeptide stability depends on temperature, light exposure, humidity, and time. Proper storage preserves peptide integrity and ensures reliable research outcomes.\n\n### Lyophilized (Freeze-Dried) Peptides\n\nLyophilized peptides are more stable than reconstituted ones but still require proper storage:\n\n- Store at -20\u00b0C for long-term stability\n- Keep away from direct light\n- Minimize exposure to humidity\n- Avoid repeated temperature changes\n\n## Reconstituted Peptide Storage\n\nOnce reconstituted, peptides become more susceptible to degradation:\n\n- Refrigerate at 2\u20138\u00b0C\n- Use within 7\u201314 days for most peptides\n- Some peptides may require shorter timeframes\n- Never freeze reconstituted peptides unless specified\n\n## Avoiding Freeze-Thaw Cycles\n\nRepeated freezing and thawing degrades peptides. If you need to store reconstituted peptides for longer periods:\n\n- Divide into single-use aliquots before freezing\n- Thaw only the amount needed for each use\n- Discard unused portions after thawing\n\n## Environmental Factors\n\n### Light\n\nMany peptides are photosensitive. Store in amber vials or opaque containers. Avoid prolonged exposure to light during handling.\n\n### Humidity\n\nMoisture absorption can lead to hydrolysis and degradation. Use desiccant packs in storage containers and allow vials to reach room temperature before opening to prevent condensation.\n\n### Temperature Stability\n\nSome peptides have different stability profiles. Always consult published data or manufacturer recommendations for specific storage conditions. When in doubt, colder storage is generally better for lyophilized material.",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(18),
                'views_count' => 1320,
                'image_index' => 3,
            ],
            [
                'title' => 'Safe Lab Practices for Peptide Handling',
                'slug' => 'safe-lab-practices-peptide-handling',
                'category' => 'Safety',
                'category_slug' => 'safety',
                'tag' => 'safety',
                'excerpt' => 'Essential safety protocols for handling peptides in a research setting, including sterile technique, waste disposal, and emergency procedures.',
                'icon' => 'shield',
                'read_minutes' => 9,
                'author_name' => 'SafetyFirst',
                'author_badge' => 'Moderator',
                'metadata' => [
                    'difficulty' => 'Beginner',
                    'guide_type' => 'Guide',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Set Up a Clean Workspace', 'text' => 'Designate a clean, uncluttered area for peptide handling. Disinfect surfaces before and after each session.', 'icon' => 'shield'],
                        ['title' => 'Use Personal Protective Equipment', 'text' => 'Always wear nitrile gloves, safety glasses, and a lab coat when handling peptides. Change gloves between different compounds.', 'icon' => 'shield'],
                        ['title' => 'Follow Sterile Technique', 'text' => 'Wipe all vial tops with alcohol swabs, use sterile syringes, and never touch the needle or vial opening.', 'icon' => 'flask'],
                        ['title' => 'Dispose of Waste Properly', 'text' => 'Use a sharps container for needles and syringes. Follow local regulations for biohazard waste disposal.', 'icon' => 'box'],
                    ],
                ],
                'body' => "## Why Safety Matters\n\nPeptide research requires careful handling to ensure both researcher safety and experimental integrity. Contamination or improper handling can compromise results and pose health risks.\n\n## Essential Equipment\n\n- Nitrile gloves (powder-free)\n- Safety glasses\n- Lab coat or designated clothing\n- Alcohol swabs (70% isopropyl)\n- Sharps disposal container\n- Sterile syringes and needles\n\n## Sterile Technique\n\nMaintaining sterility is critical when handling peptides:\n\n- Clean all work surfaces before and after use\n- Wipe vial septa with alcohol and let dry\n- Use a fresh, sterile syringe for each session\n- Never reuse needles or syringes\n- Keep vials capped when not in use\n\n## Workspace Organization\n\nA well-organized workspace reduces the risk of errors and accidents:\n\n- Keep only the materials you need within reach\n- Separate clean and waste areas\n- Label everything clearly and immediately\n- Have a spill kit accessible\n- Work in a well-ventilated area\n\n## Emergency Procedures\n\n### Spills\n\n- Contain the spill immediately using absorbent materials\n- Clean with appropriate disinfectant\n- Dispose of contaminated materials as biohazard waste\n- Document the incident\n\n### Needle Sticks\n\n- Wash the area thoroughly with soap and water\n- Seek medical attention\n- Report the incident according to your protocol\n\n## Waste Disposal\n\n- Dispose of sharps in approved containers\n- Never recap used needles\n- Follow local regulations for chemical and biohazard waste\n- Do not pour reconstituted peptides down the drain",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(15),
                'views_count' => 980,
                'image_index' => 4,
            ],
            [
                'title' => 'Navigating Peptide Research Studies',
                'slug' => 'navigating-peptide-research-studies',
                'category' => 'Research',
                'category_slug' => 'research',
                'tag' => 'research-methods',
                'excerpt' => 'A guide to finding, reading, and interpreting published research on peptides, including how to evaluate study quality and relevance.',
                'icon' => 'document',
                'read_minutes' => 11,
                'author_name' => 'ResearchReader',
                'author_badge' => 'Verified Researcher',
                'metadata' => [
                    'difficulty' => 'Intermediate',
                    'guide_type' => 'Guide',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Find Relevant Studies', 'text' => 'Use PubMed, Google Scholar, and other academic databases. Search by peptide name, sequence, or mechanism of action.', 'icon' => 'search'],
                        ['title' => 'Evaluate Study Design', 'text' => 'Look at sample size, controls, blinding, and statistical methods. These determine the reliability of the findings.', 'icon' => 'chart'],
                        ['title' => 'Compare Across Sources', 'text' => 'Cross-reference findings from multiple independent studies. Consistent results across different labs strengthen the evidence.', 'icon' => 'library'],
                        ['title' => 'Stay Current with New Research', 'text' => 'Set up alerts for new publications on specific peptides or topics. The research landscape evolves rapidly.', 'icon' => 'bell'],
                    ],
                ],
                'body' => "## The Research Landscape\n\nThe peptide research field is growing rapidly. Staying informed requires knowing where to look and how to evaluate what you find.\n\n## Finding Research\n\n### Key Databases\n\n- **PubMed** \u2014 The most comprehensive biomedical literature database\n- **Google Scholar** \u2014 Broad search with citation tracking\n- **ResearchGate** \u2014 Direct access to authors and full-text papers\n- **PubMed Central (PMC)** \u2014 Free full-text versions of many studies\n\n### Search Tips\n\n- Use both common names and systematic names\n- Include CAS numbers for precision\n- Filter by publication date for recent research\n- Review cited references for foundational studies\n\n## Evaluating Study Quality\n\nNot all studies are equal. Consider:\n\n### Sample Size\n\nSmall studies (n < 10) may have limited statistical power. Larger sample sizes generally provide more reliable results.\n\n### Controls\n\nLook for proper control groups. Placebo-controlled, double-blind studies are the gold standard for clinical research.\n\n### Statistical Analysis\n\nCheck that appropriate statistical tests were used and that effect sizes are reported alongside p-values.\n\n## Understanding Study Limitations\n\nEvery study has limitations. Responsible interpretation requires acknowledging them:\n\n- Animal models may not translate directly\n- In vitro results need in vivo confirmation\n- Short-term studies may miss long-term effects\n- Funding sources can introduce bias\n\n## Building a Reference Library\n\nOrganize your research findings for easy reference:\n\n- Use a reference manager like Zotero or Mendeley\n- Tag studies by peptide, mechanism, and findings\n- Annotate PDFs with your observations\n- Share relevant findings with the community",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(12),
                'views_count' => 760,
                'image_index' => 5,
            ],
            [
                'title' => 'How to Evaluate Peptide Suppliers',
                'slug' => 'how-to-evaluate-peptide-suppliers',
                'category' => 'Sourcing',
                'category_slug' => 'sourcing',
                'tag' => 'sourcing',
                'excerpt' => 'A practical framework for assessing peptide suppliers, including red flags, green flags, and questions to ask before purchasing.',
                'icon' => 'star',
                'read_minutes' => 10,
                'author_name' => 'VetVendor',
                'author_badge' => 'Community Guide',
                'metadata' => [
                    'difficulty' => 'Beginner',
                    'guide_type' => 'Guide',
                    'compound' => null,
                    'steps' => [
                        ['title' => 'Check for Third-Party Lab Testing', 'text' => 'Reputable suppliers provide batch-specific COAs from independent labs. Verify the testing lab is legitimate.', 'icon' => 'shield'],
                        ['title' => 'Read Community Reviews', 'text' => 'Check vendor reviews on the community platform. Look for patterns in feedback rather than isolated reviews.', 'icon' => 'users'],
                        ['title' => 'Evaluate Communication and Transparency', 'text' => 'Responsive, transparent suppliers who answer questions thoroughly are more likely to be reliable.', 'icon' => 'message'],
                        ['title' => 'Compare Pricing Against Market', 'text' => 'Prices far below market average are a red flag. Quality peptides require quality manufacturing processes.', 'icon' => 'chart'],
                    ],
                ],
                'body' => "## Why Supplier Selection Matters\n\nThe quality of your research depends on the quality of your materials. Selecting a reliable supplier is one of the most important decisions you will make.\n\n## Green Flags\n\n- **Third-party lab testing** \u2014 COAs from independent, accredited labs\n- **Batch-specific results** \u2014 Testing matched to your specific batch, not generic results\n- **Clear communication** \u2014 Responsive to questions about sourcing, testing, and manufacturing\n- **Established reputation** \u2014 Consistent positive feedback over time\n- **Transparent policies** \u2014 Clear shipping, return, and refund policies\n\n## Red Flags\n\n- No COA or refusal to provide testing documentation\n- Only vague or heavily watermarked COAs\n- Prices significantly below market average\n- Poor or evasive communication\n- Multiple negative reviews about quality or shipping\n- No clear contact information or physical address\n\n## Questions to Ask Suppliers\n\n- Do you provide batch-specific COAs from third-party labs?\n- What is your peptide synthesis process?\n- What purity testing methods do you use (HPLC, MS)?\n- What is your policy on damaged or compromised products?\n- How do you handle temperature control during shipping?\n\n## Using the Community Vendor Review System\n\nThe community vendor review platform allows you to:\n\n- Read detailed reviews from verified purchasers\n- View lab test results submitted by community members\n- Compare ratings across multiple suppliers\n- Report suspicious vendor activity\n\n## Making an Informed Decision\n\nTake your time when selecting a supplier. Cross-reference information from multiple sources, ask questions, and start with small orders to evaluate quality before committing to larger purchases.\n\nThe community is here to help. If you are unsure about a supplier, ask in the discussions section \u2014 experienced members are often happy to share their insights.",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(10),
                'views_count' => 1650,
                'image_index' => 6,
            ],
        ];

        $faqs = [
            [
                'title' => 'What exactly are peptides?',
                'slug' => 'what-are-peptides',
                'category' => 'General',
                'category_slug' => 'general',
                'tag' => 'basics',
                'excerpt' => 'Peptides are short chains of amino acids that serve as signaling molecules in the body. They are smaller and more targeted than proteins.',
                'icon' => 'question',
                'read_minutes' => 3,
                'author_name' => 'PeptideGuide',
                'author_badge' => 'Contributor',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Peptides are short chains of amino acids, typically 2\u201350 residues long, connected by peptide bonds. They occur naturally in all living organisms and act as signaling molecules, influencing a wide range of biological processes. Unlike proteins, which are larger and more complex, peptides are more specific in their interactions and can be synthesized in laboratories for research purposes. They are studied across many fields including cell biology, endocrinology, and pharmacology.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(30),
                'views_count' => 3200,
            ],
            [
                'title' => 'How should I store peptide vials?',
                'slug' => 'how-to-store-peptide-vials',
                'category' => 'Storage',
                'category_slug' => 'storage',
                'tag' => 'storage',
                'excerpt' => 'Lyophilized peptides should be stored at -20\u00b0C, protected from light and moisture. Reconstituted peptides go in the refrigerator at 2\u20138\u00b0C.',
                'icon' => 'question',
                'read_minutes' => 3,
                'author_name' => 'StableGuide',
                'author_badge' => 'Contributor',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Lyophilized (freeze-dried) peptides should be stored in a freezer at -20\u00b0C, away from direct light and moisture. Avoid repeated freeze-thaw cycles by keeping them in a frost-free freezer. Once reconstituted, most peptides should be refrigerated at 2\u20138\u00b0C and used within 7\u201314 days. Some peptides may have specific storage requirements, so always check the manufacturer recommendations. Never freeze reconstituted peptides unless explicitly stated. For long-term storage of reconstituted peptides, consider dividing into single-use aliquots before freezing.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(28),
                'views_count' => 2800,
            ],
            [
                'title' => 'What does reconstitution mean?',
                'slug' => 'what-does-reconstitution-mean',
                'category' => 'General',
                'category_slug' => 'general',
                'tag' => 'reconstitution',
                'excerpt' => 'Reconstitution is the process of dissolving lyophilized (freeze-dried) peptide powder into a sterile liquid solution for research use.',
                'icon' => 'question',
                'read_minutes' => 2,
                'author_name' => 'LabProtocols',
                'author_badge' => 'Verified Researcher',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Reconstitution is the process of dissolving lyophilized (freeze-dried) peptide powder into a sterile liquid solution, typically bacteriostatic water or sterile water. This must be done carefully to preserve peptide integrity: inject the solvent slowly down the inner wall of the vial, then gently swirl to dissolve. Never shake the vial, as this can damage the peptide structure. The concentration depends on how much solvent you add, so precise measurement is important.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(26),
                'views_count' => 2500,
            ],
            [
                'title' => 'How do I know if a source is reputable?',
                'slug' => 'how-to-know-if-source-is-reputable',
                'category' => 'Sourcing',
                'category_slug' => 'sourcing',
                'tag' => 'sourcing',
                'excerpt' => 'Check for third-party lab testing, community reviews, transparent communication, and batch-specific Certificates of Analysis.',
                'icon' => 'question',
                'read_minutes' => 3,
                'author_name' => 'VetVendor',
                'author_badge' => 'Community Guide',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'A reputable supplier should provide batch-specific Certificates of Analysis (COAs) from independent, accredited laboratories. Look for consistent positive community reviews over time, responsive and transparent communication, and clear policies. Red flags include refusal to provide testing, prices well below market average, poor communication, and multiple negative reviews. Always cross-reference information from multiple sources, and use the community vendor review system to check ratings and lab test results submitted by other members.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(24),
                'views_count' => 2300,
            ],
            [
                'title' => 'What is peptide purity and why does it matter?',
                'slug' => 'what-is-peptide-purity',
                'category' => 'Sourcing',
                'category_slug' => 'sourcing',
                'tag' => 'purity',
                'excerpt' => 'Purity refers to the percentage of desired peptide in a sample. Higher purity means fewer impurities and more reliable research results.',
                'icon' => 'question',
                'read_minutes' => 3,
                'author_name' => 'QualityCheck',
                'author_badge' => 'Lab Analyst',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Peptide purity refers to the percentage of the sample that consists of the desired peptide. Research-grade peptides typically range from 95% to 99%+ purity. The remaining percentage may include truncated sequences, oxidation products, residual solvents, or other synthesis byproducts. Higher purity is important because impurities can confound research results, introduce variability, and compromise experimental validity. Purity is most commonly measured using HPLC (High-Performance Liquid Chromatography), and the results should be documented in a Certificate of Analysis.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(22),
                'views_count' => 2100,
            ],
            [
                'title' => 'What equipment do I need for peptide research?',
                'slug' => 'what-equipment-needed-peptide-research',
                'category' => 'Getting Started',
                'category_slug' => 'getting-started',
                'tag' => 'basics',
                'excerpt' => 'Essential equipment includes sterile syringes, bacteriostatic water, alcohol swabs, gloves, storage containers, and a sharps disposal container.',
                'icon' => 'question',
                'read_minutes' => 2,
                'author_name' => 'PeptideGuide',
                'author_badge' => 'Contributor',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Basic equipment for peptide research includes: sterile syringes and needles (insulin syringes are commonly used), bacteriostatic water or sterile water for reconstitution, alcohol swabs for sanitizing vial tops, nitrile gloves for safe handling, a sharps disposal container, storage containers for refrigeration, and labels for marking vials with contents and dates. A clean, organized workspace with good lighting is also essential. For more advanced work, you may want a pH meter, sterile vials, and a refrigerator with temperature monitoring.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(20),
                'views_count' => 1900,
            ],
            [
                'title' => 'How long do reconstituted peptides last?',
                'slug' => 'how-long-reconstituted-peptides-last',
                'category' => 'Storage',
                'category_slug' => 'storage',
                'tag' => 'storage',
                'excerpt' => 'Most reconstituted peptides remain stable for 7\u201314 days when refrigerated at 2\u20138\u00b0C. Stability varies by peptide.',
                'icon' => 'question',
                'read_minutes' => 2,
                'author_name' => 'StableGuide',
                'author_badge' => 'Contributor',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Most reconstituted peptides remain stable for 7\u201314 days when stored properly in a refrigerator at 2\u20138\u00b0C. However, stability varies significantly between different peptides. Some may degrade within days, while others remain stable for several weeks. Factors affecting stability include temperature, light exposure, pH, and the specific amino acid sequence. Always check published stability data for your specific peptide. Discard the solution if it becomes cloudy, develops particulates, or exceeds the recommended use-by date. When in doubt, it is safer to prepare fresh solution.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(18),
                'views_count' => 1700,
            ],
            [
                'title' => 'Are there legal considerations for peptide research?',
                'slug' => 'legal-considerations-peptide-research',
                'category' => 'Safety',
                'category_slug' => 'safety',
                'tag' => 'legal',
                'excerpt' => 'Legal status varies by country and jurisdiction. Research peptides are intended for laboratory use only and may be regulated differently depending on location.',
                'icon' => 'question',
                'read_minutes' => 3,
                'author_name' => 'SafetyFirst',
                'author_badge' => 'Moderator',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'The legal status of research peptides varies by country, state, and municipality. In many jurisdictions, peptides are sold for research and laboratory use only, not for human consumption. Some peptides may be regulated as controlled substances in certain regions. It is your responsibility to understand and comply with applicable laws in your jurisdiction. This includes import/export regulations, possession limits, and permitted uses. The community platform cannot provide legal advice \u2014 consult a legal professional for guidance specific to your situation.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(16),
                'views_count' => 1550,
            ],
            [
                'title' => 'What is the difference between research peptides and supplements?',
                'slug' => 'peptides-vs-supplements',
                'category' => 'General',
                'category_slug' => 'general',
                'tag' => 'basics',
                'excerpt' => 'Research peptides are laboratory compounds used for scientific study, while supplements are commercially available products intended for general use.',
                'icon' => 'question',
                'read_minutes' => 2,
                'author_name' => 'PeptideGuide',
                'author_badge' => 'Contributor',
                'metadata' => ['difficulty' => 'Beginner'],
                'body' => 'Research peptides are laboratory-synthesized compounds intended for scientific study and experimental purposes. They are typically lyophilized powders that require reconstitution and are sold with purity analysis and documentation. Dietary supplements, on the other hand, are commercially available products intended for general use, often sold in pre-measured doses or capsules. The key differences are: research peptides come with purity data and are for laboratory use, while supplements are formulated for consumer use and do not typically provide batch-specific analytical data.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(14),
                'views_count' => 1400,
            ],
            [
                'title' => 'How do I calculate peptide dosage for research?',
                'slug' => 'how-to-calculate-peptide-dosage',
                'category' => 'Protocols',
                'category_slug' => 'protocols',
                'tag' => 'reconstitution',
                'excerpt' => 'Dosage depends on the peptide amount, added solvent volume, and desired concentration. Use a peptide calculator tool for accuracy.',
                'icon' => 'question',
                'read_minutes' => 4,
                'author_name' => 'LabProtocols',
                'author_badge' => 'Verified Researcher',
                'metadata' => ['difficulty' => 'Intermediate'],
                'body' => 'To calculate concentration, divide the peptide amount (in mg) by the volume of solvent added (in mL). For example, reconstituting a 5 mg vial with 2 mL of bacteriostatic water gives a concentration of 2.5 mg/mL. To find the volume needed for a specific dose, divide the desired dose (in mg or mcg) by the concentration. Always double-check your math and use a peptide calculator tool to avoid errors. Consider the peptide purity when calculating: if purity is 98%, the actual peptide content is slightly less than the stated amount.',
                'status' => 'published',
                'published_at' => $now->copy()->subDays(12),
                'views_count' => 1250,
            ],
        ];

        $research = [
            [
                'title' => 'Mechanism of Action: How Peptides Interact with Cellular Receptors',
                'slug' => 'mechanism-of-action-peptide-receptors',
                'category' => 'Mechanisms',
                'category_slug' => 'mechanisms',
                'tag' => 'mechanism',
                'excerpt' => 'An overview of how peptide hormones and signaling molecules bind to cell surface receptors and initiate intracellular signaling cascades.',
                'icon' => 'flask',
                'read_minutes' => 14,
                'author_name' => 'BioResearch',
                'author_badge' => 'Researcher',
                'metadata' => [
                    'compound' => 'General Peptide Signaling',
                    'also_known_as' => 'GPCR Signaling',
                    'research_phase' => 'Established',
                    'references' => '1. Alberts B, et al. Molecular Biology of the Cell. 6th ed. Garland Science; 2014.\n2. Pierce KL, et al. Nat Rev Mol Cell Biol. 2002;3(9):639-650.\n3. Luttrell LM, et al. Cell Signal. 2010;22(10):1377-1384.',
                ],
                'body' => "## Introduction to Peptide Signaling\n\nPeptides exert their biological effects primarily through interaction with cell surface receptors. The most common class is G protein-coupled receptors (GPCRs), which represent the largest family of membrane receptors in the human genome.\n\n## Receptor Binding\n\nWhen a peptide ligand binds to its cognate receptor, it induces a conformational change that activates intracellular signaling pathways. This process is highly specific: even small changes in peptide sequence can dramatically alter receptor affinity and activation.\n\n### Key Concepts\n\n- **Affinity** \u2014 The strength of binding between a peptide and its receptor\n- **Efficacy** \u2014 The ability of a bound peptide to produce a biological response\n- **Selectivity** \u2014 The preference of a peptide for one receptor subtype over others\n\n## Signal Transduction Pathways\n\nUpon activation, GPCRs interact with heterotrimeric G proteins, which in turn modulate various effectors:\n\n- **Adenylyl cyclase** \u2014 Regulates cAMP levels\n- **Phospholipase C** \u2014 Generates IP3 and DAG\n- **Ion channels** \u2014 Modulates membrane potential\n\n## Implications for Research\n\nUnderstanding these mechanisms allows researchers to predict peptide effects, design analogues with improved properties, and identify potential therapeutic applications. The structure-activity relationship (SAR) of peptides is a cornerstone of modern peptide research.",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(35),
                'views_count' => 890,
                'image_index' => 0,
            ],
            [
                'title' => 'Stability and Degradation Pathways of Synthetic Peptides',
                'slug' => 'stability-degradation-synthetic-peptides',
                'category' => 'Chemistry',
                'category_slug' => 'chemistry',
                'tag' => 'stability',
                'excerpt' => 'A review of the chemical degradation pathways affecting synthetic peptides, including hydrolysis, oxidation, and deamidation, with strategies for improving stability.',
                'icon' => 'flask',
                'read_minutes' => 16,
                'author_name' => 'ChemReview',
                'author_badge' => 'Contributor',
                'metadata' => [
                    'compound' => 'General Peptide Chemistry',
                    'also_known_as' => 'Peptide Degradation',
                    'research_phase' => 'Established',
                    'references' => '1. Manning MC, et al. Pharm Res. 2010;27(4):544-575.\n2. Patel K, et al. AAPS PharmSciTech. 2015;16(3):488-498.\n3. Nguyen LT, et al. Pharmaceuticals. 2023;16(2):265.',
                ],
                'body' => "## Chemical Stability of Peptides\n\nPeptides are susceptible to various chemical degradation pathways. Understanding these is essential for proper handling, storage, and experimental design.\n\n## Major Degradation Pathways\n\n### Hydrolysis\n\nPeptide bonds can undergo hydrolysis, particularly at aspartic acid residues. This reaction is accelerated by acidic or basic conditions and elevated temperatures.\n\n### Oxidation\n\nMethionine, cysteine, and tryptophan residues are particularly susceptible to oxidation. This can occur during storage, handling, or exposure to light and air.\n\n### Deamidation\n\nAsparagine and glutamine residues can undergo deamidation, converting to aspartic and glutamic acids respectively. This reaction is influenced by pH, temperature, and the adjacent amino acid sequence.\n\n## Strategies for Improving Stability\n\n- **Lyophilization** \u2014 Removes water and reduces hydrolysis rates\n- **Low temperature storage** \u2014 Slows all degradation pathways\n- **pH optimization** \u2014 Minimizes specific degradation reactions\n- **Protective packaging** \u2014 Limits light and oxygen exposure\n\n## Analytical Methods\n\nStability is typically monitored using:\n\n- HPLC for purity assessment\n- Mass spectrometry for degradation product identification\n- Bioassays for activity retention",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(28),
                'views_count' => 720,
                'image_index' => 1,
            ],
            [
                'title' => 'HPLC Method Development for Peptide Analysis',
                'slug' => 'hplc-method-development-peptide-analysis',
                'category' => 'Analytical',
                'category_slug' => 'analytical',
                'tag' => 'hplc',
                'excerpt' => 'Best practices for developing and optimizing HPLC methods for peptide purity analysis, including column selection, mobile phase composition, and gradient design.',
                'icon' => 'flask',
                'read_minutes' => 18,
                'author_name' => 'LabProtocols',
                'author_badge' => 'Verified Researcher',
                'metadata' => [
                    'compound' => 'General Peptide Analysis',
                    'also_known_as' => 'Peptide HPLC',
                    'research_phase' => 'Methodology',
                    'references' => '1. Mant CT, et al. J Chromatogr A. 2007;1143(1-2):6-20.\n2. Aguilar MI. HPLC of Peptides and Proteins. Humana Press; 2004.\n3. Shintani H. HPLC Analysis of Peptides. Springer; 2020.',
                ],
                'body' => "## Introduction to Peptide HPLC\n\nHigh-Performance Liquid Chromatography is the primary analytical tool for assessing peptide purity. Reversed-phase HPLC (RP-HPLC) using C18 columns is the most common configuration.\n\n## Column Selection\n\nThe choice of column significantly impacts separation quality:\n\n- **C18 columns** \u2014 Most common, good for general peptide analysis\n- **C8 columns** \u2014 Lower hydrophobicity, useful for smaller peptides\n- **C4 columns** \u2014 For larger or more hydrophobic peptides\n- **Phenyl columns** \u2014 Alternative selectivity for aromatic residues\n\n## Mobile Phase Composition\n\n### Solvents\n\n- **Water** with 0.1% TFA \u2014 Standard aqueous phase\n- **Acetonitrile** \u2014 Most common organic modifier\n- **Methanol or isopropanol** \u2014 Alternatives for specific separations\n\n### Ion-Pairing Agents\n\nTrifluoroacetic acid (TFA) is the most widely used ion-pairing agent, improving peak shape and retention. Formic acid is preferred when MS detection is used.\n\n## Gradient Design\n\nA linear gradient from 5% to 60% acetonitrile over 20-30 minutes is a good starting point for most peptides. Adjust based on:\n\n- Peptide length and hydrophobicity\n- Column dimensions\n- Desired resolution\n\n## Data Interpretation\n\nKey parameters to evaluate:\n\n- **Retention time** \u2014 Should be consistent between runs\n- **Peak symmetry** \u2014 Asymmetry factor should be close to 1\n- **Resolution** \u2014 Baseline separation from impurities\n- **Area percent** \u2014 Purity calculation",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(21),
                'views_count' => 650,
                'image_index' => 2,
            ],
            [
                'title' => 'Peptide Synthesis Methods: Solid-Phase vs. Liquid-Phase',
                'slug' => 'peptide-synthesis-solid-phase-liquid-phase',
                'category' => 'Chemistry',
                'category_slug' => 'chemistry',
                'tag' => 'synthesis',
                'excerpt' => 'A comparison of solid-phase peptide synthesis (SPPS) and liquid-phase methods, including advantages, limitations, and applications for different peptide types.',
                'icon' => 'flask',
                'read_minutes' => 15,
                'author_name' => 'ChemReview',
                'author_badge' => 'Contributor',
                'metadata' => [
                    'compound' => 'Peptide Synthesis',
                    'also_known_as' => 'SPPS vs LPPS',
                    'research_phase' => 'Established',
                    'references' => '1. Merrifield RB. J Am Chem Soc. 1963;85(14):2149-2154.\n2. Fields GB, et al. Int J Pept Protein Res. 1990;35(3):161-214.\n3. Martinez J, et al. Peptide Synthesis. Elsevier; 2023.',
                ],
                'body' => "## Overview of Synthesis Methods\n\nPeptide synthesis has evolved significantly since Merrifield introduced solid-phase peptide synthesis (SPPS) in 1963. Today, both solid-phase and liquid-phase methods are used, each with distinct advantages.\n\n## Solid-Phase Peptide Synthesis (SPPS)\n\nSPPS involves anchoring the C-terminal amino acid to an insoluble resin support and building the peptide chain through sequential coupling reactions.\n\n### Advantages\n\n- Rapid synthesis of peptides up to 50 residues\n- Easy purification by filtration after each step\n- Amenable to automation\n- Suitable for parallel synthesis of multiple peptides\n\n### Limitations\n\n- Aggregation can occur with difficult sequences\n- Excess reagents required for complete coupling\n- Final cleavage can cause side reactions\n\n## Liquid-Phase Peptide Synthesis (LPPS)\n\nLPPS is performed entirely in solution, without a solid support.\n\n### Advantages\n\n- Better suited for large-scale production\n- Easier reaction monitoring in real time\n- No cleavage step required\n- Fewer purification steps overall\n\n### Limitations\n\n- More labor-intensive\n- Requires precipitation or extraction between steps\n- Less suitable for automation\n\n## Choosing the Right Method\n\n- **SPPS** \u2014 Preferred for research-scale synthesis (up to 50 residues)\n- **LPPS** \u2014 Better for industrial-scale production or short peptides\n- **Hybrid approaches** \u2014 Combine both methods for complex targets",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(14),
                'views_count' => 580,
                'image_index' => 3,
            ],
            [
                'title' => 'Quality Control in Peptide Manufacturing: GMP Standards',
                'slug' => 'quality-control-peptide-manufacturing-gmp',
                'category' => 'Quality',
                'category_slug' => 'quality',
                'tag' => 'gmp',
                'excerpt' => 'An overview of Good Manufacturing Practice (GMP) standards for peptide production and the quality control tests that ensure product consistency and purity.',
                'icon' => 'shield',
                'read_minutes' => 13,
                'author_name' => 'QualityCheck',
                'author_badge' => 'Lab Analyst',
                'metadata' => [
                    'compound' => 'Quality Standards',
                    'also_known_as' => 'GMP Peptide',
                    'research_phase' => 'Industry Standard',
                    'references' => '1. FDA. Current Good Manufacturing Practice. 21 CFR Parts 210-211.\n2. ICH Q7. Good Manufacturing Practice Guide for Active Pharmaceutical Ingredients.\n3. USP General Chapter <787>.',
                ],
                'body' => "## GMP in Peptide Manufacturing\n\nGood Manufacturing Practice (GMP) ensures that peptide products are consistently produced and controlled according to quality standards. GMP covers all aspects of production from raw materials to finished product.\n\n## Key Quality Control Tests\n\n### Identity Testing\n\n- **Mass spectrometry** \u2014 Confirms molecular weight\n- **Amino acid analysis** \u2014 Verifies composition\n- **Sequencing** \u2014 Confirms primary structure\n\n### Purity Testing\n\n- **HPLC** \u2014 Quantitative purity assessment\n- **Capillary electrophoresis** \u2014 Complementary separation method\n- **LC-MS** \u2014 Coupled purity and identity confirmation\n\n### Impurity Testing\n\n- **Related substances** \u2014 Truncated sequences and byproducts\n- **Residual solvents** \u2014 From synthesis and purification\n- **Heavy metals** \u2014 From reagents and equipment\n\n## Documentation Requirements\n\nGMP requires comprehensive documentation:\n\n- Batch production records\n- Standard operating procedures\n- Deviations and investigations\n- Stability data\n\n## Certificate of Analysis\n\nA GMP-compliant COA includes:\n\n- Batch number and manufacturing date\n- Test methods and specifications\n- Results for each quality attribute\n- Expiry date and storage conditions",
                'status' => 'published',
                'published_at' => $now->copy()->subDays(7),
                'views_count' => 430,
                'image_index' => 4,
            ],
        ];

        foreach ($guides as $data) {
            CommunityContentItem::create(array_merge(['type' => 'guide'], $data));
        }

        foreach ($faqs as $data) {
            CommunityContentItem::create(array_merge(['type' => 'faq'], $data));
        }

        foreach ($research as $data) {
            CommunityContentItem::create(array_merge(['type' => 'research'], $data));
        }

        $this->command->info('Seeded ' . count($guides) . ' guides, ' . count($faqs) . ' FAQs, and ' . count($research) . ' research articles.');
    }
}
